{{- range $index, $config := .Values.configs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-service.fullname" $ }}-config-{{ $index }}
  labels:
    {{- include "base-service.labels" $ | nindent 4 }}
type: Opaque
data:
  configData: {{ $config.data | quote }}
{{- end }}
