apiVersion: v1
kind: Service
metadata:
  name: pond-server
spec:
  selector:
    app: pond-server
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9090
      targetPort: management
