name: Tests

on:
  workflow_call:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Vet
        run: make vet

      - name: Run unit tests
        run: make test

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Run integration tests
        run: make test-integration
